### ISSUE TITLE
sample code from README does not work with version 2.4.*

### ISSUE THREAD

**Issue by sovcarrillon** [FasterXML/jackson-dataformat-csv#49]
Using the following sample code from _Usage_ section in README does not work with version 2.4.x :

```
// Read schema from the first line; start with bootstrap instance
// to enable reading of schema from the first line
// NOTE: reads schema and uses it for binding
CsvSchema bootstrapSchema = CsvSchema.emptySchema().withHeader();
ObjectMapper mapper = new CsvMapper();
mapper.reader(Pojo.class).with(bootstrapSchema).readValue(json);
```

I get the following exception :

```
Exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.core.util.BufferRecycler.allocCharBuffer(II)[C
    at com.fasterxml.jackson.dataformat.csv.impl.TextBuffer.findBuffer(TextBuffer.java:178)
    at com.fasterxml.jackson.dataformat.csv.impl.TextBuffer.emptyAndGetCurrentSegment(TextBuffer.java:397)
    at com.fasterxml.jackson.dataformat.csv.impl.CsvReader.nextString(CsvReader.java:566)
    at com.fasterxml.jackson.dataformat.csv.CsvParser._readHeaderLine(CsvParser.java:579)
    at com.fasterxml.jackson.dataformat.csv.CsvParser._handleStartDoc(CsvParser.java:451)
    at com.fasterxml.jackson.dataformat.csv.CsvParser.nextToken(CsvParser.java:414)
    at com.fasterxml.jackson.databind.ObjectReader._bindAndReadValues(ObjectReader.java:1331)
    at com.fasterxml.jackson.databind.ObjectReader.readValues(ObjectReader.java:1157)
    at com.Test.main(Test.java:56)
```

Code works properly with version 2.3.3 and below.
